### ISSUE TITLE
Swiper Slider does not fire slideChange event for first/last slide on loop+autoplay mode

### ISSUE THREAD

**Issue by amiriahmad72** [nolimits4web/swiper#3050]
* Swiper Version: 4.4.2
* Platform/Target and Browser Versions: Windows 10 (CHROME).

### I just do this:
`var mySwiper = new Swiper('.swiper-container', {`
`speed : 600,`
`loop : true,`
`autoplay : true,`
`on : {`
`slideChange: function () { /* do something */ }`
`}`
`});`

### Expected Behavior

- for first slide:
Swiper Slider fire slideChange event each time active slide change to first slide.
- for last slide:
Swiper Slider fire slideChange event each time active slide change to last slide.
- for others slides:
Swiper Slider fire slideChange event each time active slide change to the slide.

### Actual Behavior
- for first slide:

1. Swiper Slider fire slideChange event when active slide changed by user to first slide In reverse direction. 👍
2. Swiper Slider does not fire slideChange event when active slide changed automatically from last slide to first slide. 👎
- for last slide:
1. Swiper Slider does not fire slideChange event when active slide changed by user to last slide In reverse direction.👎
2. Swiper Slider fire slideChange event when active slide changed automatically to last slide.👍
- for others slides:
like Expected Behavior.👍

**Comment by emb03** [comment]
I believe this is what is causing my images to ghost one on top of the other when autoplay is on.  It only happens when it gets to the first slide in the loop. Any workaround? Client is complaining.

**Comment by BeAce** [comment]
I solved it this way.
```js
mySwiper.on('touchEnd', () => {
      const lastOneIndex = N; // N is the length of swiper-slide
      const offset = this.$refs.lastOneRef.getBoundingClientRect();
      const { left, width } = offset;
      if (left > 0 && left + width <= window.innerWidth) {
         // The last one show, do what you want to do
      } else {
         // The last one leave, stop the last one things
      }
})
```

**Comment by emb03** [comment]
My ghosting image of last slide to first was fixed by supplying missing semi-colons in css file.

**Comment by MarikKV** [comment]
I have same problem when I used multiple swipers on my page. Make sure you create new Swiper obj and call this method to them directly.

**Comment by webgrafia** [comment]
same problem

**Comment by bizq** [comment]
I just remove the loop

**Comment by patrickbenjamin1** [comment]
This really odd bug still exists in the React Swiper - I've tried using the onTouchEnd event with a timeout to ensure that any syncronous state updates are done before I try and access the realIndex but the value for realIndex doesn't seem to be updated when you land on the first slide. Is there a null check somewhere that's not accounting for 0?

**Comment by radhouenchbinou** [comment]
Try using swiperslidechange instead of slideChange it solved my problem

**Comment by karocksjoelee** [comment]
#All [Swiper events](https://swiperjs.com/swiper-api#events) are available as native DOM events but with lowercase names and swiper prefix (configurable via events-prefix parameter). E.g. slideChange becomes swiperslidechange.

**Comment by Bonny-kato** [comment]
For me i just removed `loop` property and leave `autoplay` and it works

**Comment by smejiaconxium** [comment]
> #All [Swiper events](https://swiperjs.com/swiper-api#events) are available as native DOM events but with lowercase names and swiper prefix (configurable via events-prefix parameter). E.g. slideChange becomes swiperslidechange.

This is exactly right, after hours of research this ended up being not only the correct solution but the cleanest. Thank You!
