### ISSUE TITLE
Swiper Svelte doesn't support SSR under Sapper JS

### ISSUE THREAD

**Issue by igolkotek** [nolimits4web/swiper#3961]
This is a (multiple allowed):
* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.5.
* Platform/Target and Browser Versions: Ubuntu 20.04, Firefox 83.

### What you did
Sapper bundle compilation in dev mode fails both whether Swiper is added according to Swiper site example or with Mount according to Sapper recommendations.

**Comment by btakita** [comment]
Would it be possible to include the source *.svelte components in the build?

**Comment by vltansky** [comment]
@igolkotek @btakita can you confirm that it's fixed ?

**Comment by silllli** [comment]
Same problem here.

When I import the *.svelte components directly, Rollup fails to import some helper files like `./init-swiper` and `./ultis`, or am I missing something?

**Comment by zakkor** [comment]
I've managed to fix it in a fork just enough so we can keep using Swiper in our project, however I'm not sure what a proper fix would be because I'm not familiar with the build process (which seems fairly complex).

It seems like the main issue is that when you import something in a Svelte project, it expects to compile the component along with all of its dependencies, through each projects' build process.
In this repository however, none of the built JS files that the Svelte components are trying to import are actually included, so Svelte complains that it can't find the files and the build doesn't work.

Here are the changes I made in order to get it to work: https://github.com/zakkor/swiper/commit/0984204eafe301ab9bce8b717117e548a1edea19

I fixed the import paths so they point to the correct files, and included some of the needed pre-built JS files in the `build` dir (esm version only)

**Comment by vltansky** [comment]
@zakkor could you take a look at the suggested change in #4061 PR? I think this should work well.

**Comment by silllli** [comment]
For anyone wondering: this works now, but you need to load the Swiper module dynamically in the `onMount` function. There is an example in the [Sapper docs](https://sapper.svelte.dev/docs#Third-party_libraries_that_depend_on_window).

**Comment by brian-hay** [comment]
@silllli any chance you can provide a working code snippet? I managed to get the imports working using onMount, and the first slide displays with left/right carets overlaid but empty pagination tag and navigation isn't possible - it's just stuck on first slide, with no console errors.

**Comment by silllli** [comment]
Maybe you forgot to import and tell Swiper about the navigation and pagination modules?

I didn’t test it, but something like this should work:

```
<script>
  import SwiperCore, { Navigation, Pagination } from 'swiper';

  // tell swiper to use navigation and pagination modules
  SwiperCore.use([Navigation, Pagination]);

  let Swiper;
  let SwiperSlide;

  onMount(async () => {
    // dynamically import swiper module
    const SwiperSvelteModule = await import('swiper/svelte');
    Swiper = SwiperSvelteModule.Swiper;
    SwiperSlide = SwiperSvelteModule.SwiperSlide;
  }
</script>

// NOTE: the swiper stylesheets need to be imported as well

<svelte:component
  this={Swiper}
  navigation={{
    nextEl: '.swiper-button-next',
    prevEl: '.swiper-button-prev',
  }}
  pagination={{
    el: '.swiper-pagination',
    type: 'bullets',
    clickable: true,
  }}>

  <svelte:component this={SwiperSlide}>
    Slide content
  </svelte:component>

  <div class="swiper-pagination" slot="container-end"></div>

  <div class="swiper-button-prev" slot="container-end"></div>
  <div class="swiper-button-next" slot="container-end"></div>
</svelte:component>
```

You also need to import the needed Swiper stylesheets. I do it in the style tag via SASS, the Swiper docs import in the `<script>` tag.

I hope it helps!

**Comment by brian-hay** [comment]
Thanks for the the comprehensive response @silllli . I had most of that in place but I modified to match exactly and no change as yet. I'll keep trying.

**Comment by silllli** [comment]
I looked at it again since this bugged me. 🤓

Some adjustments were needed—I experienced a similar scenario that you describe (being stuck on the first slide) after running my code. I then added the `slidesPerView` param, and it worked! Maybe adding it will already do the trick for you. 

Here is my actually working code:

```
<script>
  import { onMount } from 'svelte';
  import SwiperCore, { Navigation, Pagination } from 'swiper';

  // tell swiper to use navigation and pagination modules
  SwiperCore.use([Navigation, Pagination]);

  let Swiper;
  let SwiperSlide;

  onMount(async () => {
    // dynamically import swiper module
    const SwiperSvelteModule = await import('swiper/svelte');
    Swiper = SwiperSvelteModule.Swiper;
    SwiperSlide = SwiperSvelteModule.SwiperSlide;
  })
</script>

<style lang="scss">
  :global {
    @import 'swiper/swiper';
    @import 'swiper/components/navigation/navigation';
    @import 'swiper/components/pagination/pagination';

    .swiper-slide {
      height: 500px;
      background: red;
    }
  }
</style>

<svelte:component
  this={Swiper}
  navigation={true}
  pagination={{
    type: 'bullets',
    clickable: true,
  }}
  slidesPerView={1}
  spaceBetween={100}>

  <svelte:component this={SwiperSlide}>
    Slide content 1
  </svelte:component>

  <svelte:component this={SwiperSlide}>
    Slide content 2
  </svelte:component>

  <svelte:component this={SwiperSlide}>
    Slide content 3
  </svelte:component>
</svelte:component>
```

I also found this in the docs:

> Note, Swiper Svelte component will create required elements for Navigation, Pagination and Scrollbar if you pass these params without specifying its elements (e.g. without navigation.nextEl, pagination.el, etc.)

So we actually don’t need to use the slots.

**Comment by brian-hay** [comment]
Thanks @silllli . Still no joy for me. Not sure what's wrong with it.

I copied and pasted the carousel from https://github.com/beyonk-adventures/svelte-carousel/blob/master/src/Carousel.svelte into my own Carousel component and that worked.

**Comment by nolimits4web** [comment]
https://swiperjs.com/svelte#using-with-sapper

**Comment by brian-hay** [comment]
@nolimits4web thanks for this but still having trouble. I'm using [SvelteKit](https://github.com/sveltejs/kit) (beta), the replacement for Sapper.

After updating swiper dependencies and imports as per new docs, the production build runs but the the carousel doesn't work (all slides are displayed at once).

The local dev build results in the following error:
![image](https://user-images.githubusercontent.com/1428000/113637977-2b081c00-96b9-11eb-9911-25bbc1e98192.png)

**Comment by thebells1111** [comment]
@brian-hay 

Did you try this yet?

[https://swiperjs.com/svelte#using-with-sapper-and-svelte-kit](https://swiperjs.com/svelte#using-with-sapper-and-svelte-kit)

**Comment by brian-hay** [comment]
@thebells1111 yes that error I posted above is after following the instructions in that link.

**Comment by vladbelozertsev** [comment]
I have this error, and solve it by import from esm. But now swiper navigation doesnt work.
I'm using svelte-kit...


> https://swiperjs.com/svelte#using-with-sapper

**Comment by davidmgrana** [comment]
any news on this? having the same issue with sveltekit, navigation won't work
